/**
 * Simple State Management for the Birth Chart Application
 * Separates User Inputs, Calculation Results, and UI State
 */

const Store = {
    // 1. User Inputs (Current settings in the form)
    inputs: {
        birthDate: '1995-01-01',
        birthTime: '12:00',
        location: {
            lon: 121.56,
            lat: 25.03,
            name: '台北市 台北市',
            city: '台北市',
            district: '121.56,25.03',
            isManual: false
        },
        gender: 'male',
        queryYear: 2026,
        houseSystem: 'placidus',
        transitDate: '',
        transitTime: ''
    },

    // 2. Calculation Results (Data generated by various cores)
    results: {
        astro: {
            planets: [],
            houses: null,
            aspects: []
        },
        ziwei: null,
        humanDesign: {
            personality: null,
            design: null,
            transit: null
        }
    },

    // 3. UI State (Visual status of the application)
    ui: {
        isLoading: false,
        activeTab: 'astro', // Future proofing
        modal: {
            isOpen: false,
            title: '',
            subtitle: '',
            content: '',
            icon: ''
        }
    },

    /**
     * Update methods to modify state
     */
    updateInputs(newInputs) {
        this.inputs = { ...this.inputs, ...newInputs };
    },

    setAstroResults(planets, houses) {
        this.results.astro.planets = planets;
        this.results.astro.houses = houses;
    },

    setZiWeiResults(data) {
        this.results.ziwei = data;
    },

    setHDResults(personality, design, transit) {
        this.results.humanDesign.personality = personality;
        this.results.humanDesign.design = design;
        this.results.humanDesign.transit = transit;
    },

    setLoading(loading) {
        this.ui.isLoading = loading;
        const loader = document.getElementById('loading');
        if (loader) {
            loader.style.display = loading ? 'flex' : 'none';
        }
    },

    showModal(config) {
        this.ui.modal = { ...this.ui.modal, ...config, isOpen: true };
        // Trigger UI update for modal
        const modal = document.getElementById('modal-overlay');
        if (modal) {
            document.getElementById('modal-title').textContent = this.ui.modal.title;
            document.getElementById('modal-subtitle').textContent = this.ui.modal.subtitle;
            document.getElementById('modal-icon').textContent = this.ui.modal.icon;

            const contentArea = document.querySelector('.interpretation-text');
            if (contentArea && config.content) {
                contentArea.innerHTML = config.content;
            }

            modal.style.display = 'flex';
        }
    },

    hideModal() {
        this.ui.modal.isOpen = false;
        const modal = document.getElementById('modal-overlay');
        if (modal) modal.style.display = 'none';
    }
};

// Export to window for global access (since we are not using modules yet)
window.AppState = Store;
